@isTest
public class Milestone1_Milestone_Batch_Update_Tst {
public static testmethod void testMilestoneBatchUpdate(){
        // Create a project with milestones
        Milestone1_Project__c         project = Milestone1_Test_Utility.sampleProject('My Project');
        List<Milestone1_Milestone__c> mList   = new List<Milestone1_Milestone__c>();
        
        insert project;
        
        for(Integer i = 0; i < 200; i++){
            mList.add( Milestone1_Test_Utility.sampleMilestone(project.Id, null, 'My Test Milestone ' + i) );
        }
        Test.StartTest();
        insert mList;
        
        // Extract milestones Ids and run in batch
        Set<Id> idSet = new Set<Id>();
        
        for(Milestone1_Milestone__c m : mList){
            idSet.add( m.Id );
        }
        
        //Test.StartTest();

        Database.executeBatch( new Milestone1_Milestone_Batch_Update(idSet) );

        Test.StopTest();

        // Test records were updated
        List<Milestone1_Milestone__c> result = [SELECT Id, LastModifiedDate, CreatedDate FROM Milestone1_Milestone__c WHERE Project__c = :project.Id];
        
        idSet.clear();
        for(Milestone1_Milestone__c m : result){
            if( m.LastModifiedDate > m.CreatedDate ){
                idSet.add( m.Id );
            }
        }
         
        //System.AssertEquals( 200, idSet.size() );
    }
}