/**************************************************************************************** 
* @Class Name  - scc_constantHelper
* @description - Common class for all static keywords
* @Created By  - CTS-Muthukumar
* @Created On - 2024-05-14
* ***************************************************************************************/ 
public class scc_constantHelper {
	public static final string STORE_NAME = 'MySavvasOrders';
    public static final string DELIVERY_GROUP_SAVVAS = 'DefaultDeliveryGroup';
    public static final string DEFAULT_CART = 'Cart';
	public static final string DEFAULT_PAYMENT_TERM = 'Z999';
    public static final string COUNTRY_US = 'US';
    public static final string COUNTRY_UNITED_STATES = 'United States';
    public static final string COUNTRY_CANADA= 'Canada';
    public static final string DEFAULT_TAX= 'Net';
    public static final Boolean FALSE_VALUE = false; 
    public static final string  STATUS_ACTIVE= 'ACTIVE';
    public static final string INVOICE_NUMBER = 'Invoice #';
    public static final string CUSTOMER_COMMUNITY_PLUS_LOGIN_USER = 'Customer Community Plus Login User';
    public static final string PO_NUMBER = 'PO#';
    public static final string OUR_SHIP_TO_LOCATIONS_ONLY = 'Our Ship-To Locations Only';
    public static final string ALL_SHIP_TO_LOCATIONS = 'All Ship-To Locations';
    public static final string CONTAINING_ISBN = 'Containing ISBN';
    public static final string ORDER_NUMBER = 'Order #';
    public static final string ZIP_POSTAL_CODE = 'Zip/Postal Code';
   	public static final string STATE_PROVINCE = 'State/Province';
    public static final string COUNTRY = 'Country';
    public static final string CUSTOMER_SAN = 'Customer SAN';
    public static final string ALL_ORDERS = 'All Orders';
    public static final string ALL = 'All';
    public static final string CART_NAME = 'Cart';
    public static final string ACTIVE = 'Active';
    public static final string WEBORD_KEYWORD='WEBORD000001';
    public static final string DEFAULT_US_CODE='0002';
    public static final string CANADA_CODE='0006';
    public static final string CUSTOMER_ACCOUNT = 'Customer Account #';
    public static final string CUSTOMER_NAME = 'Customer Name';
    public static final List<String> schoolDistrict = new List<String>{'BIA School','Catholic School','County School','Day Care','Depositories','Diocese','DOD',
        												'International School','International Distributor','Private School','Public District','Public School','School Mgmt Co','State School','Sub-District'};
    public static final List<String> DIGITAL_PRODUCT = new List<String>{'OLS','AMD','BOL','SUL','DSB','OLC'}; 
    public static final string MY_SAVVAS_ORDERS_PROFILE = 'MySavvasOrders Profile';
    public static final string SAVVAS_EXTERNAL_USERS_BASE_PROFILE = 'Savvas External Users Base Profile';
	public static final string SYSTEM_ADMINISTRATOR_PROFILE = 'System Administrator'; 
    public static final string ENTRY_POINT = '/scc_checkAccessCodeLWC/checkAccessCodeResponse/scc_checkAccessCode.checkAccessCode'; 
    public static final string FEDEX_ENTRY_POINT = '/scc_checkAccessCodeLWC/checkAccessCodeResponse/scc_checkAccessCode.checkAccessCode'; 
    public static final string RADAR_ENTRY_POINT = '/scc_documentSearchLWC/handleSubmit_OR_handleInvoice/scc_documents_RADAR_Controller.generateRADARRequest';
    public static final string MYSAVVASORDERS_GUEST_USER = 'MySavvasOrders Guest User';
    public static final string GUEST_USER = 'Guest User';
    public static final string INTERNAL_USER = 'Internal User';
    public static final string EXTERNAL_USER = 'External User';
    public statiC final string NOT_FOUND='Not found';
    public statiC final string IT_EXTERNAL_SUPPORT = 'IT External Support';
    public statiC final string GUEST = 'Guest';
    public statiC final string STATUS_NEW = 'New'; 
    public statiC final string ORIGIN_WEB = 'Web'; 
    public statiC final string INTERAL = 'Internal'; 
    public static final string EXCEPTION_TYPE_CAUGHT='Exception type caught: ';
    public static final string MESSAGE='Message: ';
    public static final string CAUSE='Cause: ';
    public static final string LINE_NUMBER='Exception type caught: ';
    public static final string STACK_RACE='Stack trace: ';
    public static final string SAVVAS_SIOP_PERMISSIONS='Savvas_SIOP_Permissions';
    public static final string INVOICE='Invoice';
    public static final string INVOICE_AND_POD='Invoice & Proof of Delivery (if available)';
    public static final string POD='Proof of Delivery (if available)';
    public static final string CREDIT_MEMO='Credit Memo';
    public static final string DEBIT_MEMO='Debit Memo';
    public static final string STATEMENT='Statement';
    public static final string INTERNATIONAL_SCHOOL='International School';
    public static final string INTERNATIONAL_DISTRIBUTOR='International Distributor';
}