global class HelloWorldMatt {
    public String hello() {
        return 'Hello World! Justice third* change test';
    }
    public String goodbye() {
        return 'Goodbye World!';
    }
    public String newline() {
        return 'New Line, quick test';
    }
    public String iShouldConflict() {
        return 'what he said! again, NEW CONFLICT!!!';
    }
    public String helloRealDev2() {
        return 'Hello yadda yadda world!';
    }
    public String justice() {
        return 'new! Attempt number two';
    }
}